version: "3.7"
services:
  neo4j:
    image: neo4j:3.5
    ports:
      - 7474:7474
      - 7687:7687
    restart: always  
    environment:
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4J_AUTH: neo4j/pass
    networks:
      - backend    
  app:
    image: malikivan/travelbook-web:latest
#    links:
#      - neo4j:neo4j
    ports:
      - 8080:8080
    restart: always
    depends_on: 
      - neo4j      
    environment:
      DB_USERNAME: neo4j
      DB_PASSWORD: pass
      DB_URI: bolt://neo4j:7687
    networks:
      - backend
      - frontend  
  site: 
    image: malikivan/travelbook-site:latest
    ports:
      - 3000:3000
    restart: always
    depends_on: 
      - app
    networks: 
      - frontend

networks:
  backend:
  frontend:      
